# https://developers.cloudflare.com/workers/wrangler/configuration

name = "sources"
compatibility_date = "2026-02-06"

compatibility_flags = [
	"nodejs_compat"
]

pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB_Ontology"
database_name = "Ontology_9494_2026-01-29"
database_id = "cdc31345-4222-4a1c-a70e-442adb6374fc"

[[d1_databases]]
binding = "DB_Auth"
database_name = "Auth"
database_id = "c547b234-05fd-4923-ab0e-689d993894ad"

[[r2_buckets]]
binding = "R2_db_backups"
bucket_name = "db-backups"
