# https://developers.cloudflare.com/workers/wrangler/configuration

name = "sources"
compatibility_date = "2025-12-18"

compatibility_flags = [
	"nodejs_compat"
]

pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB_Ontology"
database_name = "Ontology.9494.2025-12-18"
database_id = "441ed35c-dbb6-4dd0-860c-aefe18be3fc8"

[[d1_databases]]
binding = "DB_Auth"
database_name = "Auth"
database_id = "b3f48161-a488-4737-ab9a-f59c22090c80"

[[r2_buckets]]
binding = "R2_db_backups"
bucket_name = "db-backups"
